# fly.toml app configuration file generated for phonebookcliff on 2024-05-08T19:09:59-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phonebookcliff'
primary_region = 'iad'

[build]

[env]
  PORT = "3000" 

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
